### ISSUE TITLE
Body text missing

### ISSUE THREAD

**Issue by EdwardGoomba** [sanity-io/tutorial-sanity-blog-react-next#3]
Post content is missing body text. Update query to include body.

**Comment by kmelve** [comment]
Thanks for reporting! The [query does include the body](https://github.com/sanity-io/tutorial-sanity-blog-react-next/blob/master/web/pages/post.js#L51) and it to work when I run this locally. Can there be changes in your dataset that isn't published?

**Comment by EdwardGoomba** [comment]
Thanks for pointing that out :) Tutorial is missing body - cloned version of this repo works great!

**Comment by kmelve** [comment]
Ah, I didn’t check the tutorial. I’ll make sure to add that then. Thanks again!
